export const ANSIBLE_VARS_REQUEST = 'ANSIBLE_VARS_REQUEST';
export const ANSIBLE_VARS_SUCCESS = 'ANSIBLE_VARS_SUCCESS';
export const ANSIBLE_VARS_FAILURE = 'ANSIBLE_VARS_FAILURE';
export const ANSIBLE_VARS_REMOVE = 'ANSIBLE_VARS_REMOVE';
